name: Apache helloworld webApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    



jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker webApp
        run: docker build . --tag test-webapp:$(date +%s)