name: Test Env with build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:   

  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
      - run: docker build . --tag thegentl3m4n/test-webapp:v1.2       # define version here  
